# Generated by Django 6.0.4 on 2026-04-20 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCompany', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badget', models.CharField(max_length=10, unique=True)),
                ('performance', models.FloatField(default=0)),
                ('commission', models.FloatField(default=0.05)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='api.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butget', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('Prospecto', 'Prospecto'), ('Cliente', 'Cliente')], default='Prospecto', max_length=50)),
                ('priority', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='api.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='api.person')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='api.seller')),
            ],
        ),
    ]
