services:
  db:
    image: postgres:15-alpine
    container_name: crm_postgres_final
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Docker-python.dev
    container_name: crm_django_back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Docker-vite.dev
    container_name: crm_vite_front
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host"
  fastapi:
    build:
      context: ./microservicio
      dockerfile: Docker-fast.dev
    container_name: crm_fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./microservicio:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: